pipeline:
  build:
    image: centos:7
    commands:
      - yum install -y epel-release
      - yum install -y python-pip
      - pip install --upgrade pip
      - pip install pex
      - pex supervisor -c supervisord -o supervisord.pex
      - pex supervisor -c supervisorctl -o supervisorctl.pex
      - ./supervisord.pex --version

  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: "*.pex"
    checksum:
      - sha256
    when:
      event: tag
